name: ChallengeSystem
version: 0.1
author: CRAFTagain
main: de.craftagain.challengesystem.ChallengeSystem
api-version: 1.13

commands:
  settings:
    usage: /settings
    description: Einstellungen der Challenge
    aliases: s

  timer:
    usage: /timer [resume]/[stop]
    description: Fortsetzen/Stoppen des Timers